server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AuthDB
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
